### PR TITLE
Fixed the deploy URL

### PR DESCRIPTION
**Pull request by arvindr21**

### CODE REVIEW

**Comment by michelle** [comment]
Hm, the link that's there should already work! Does it not work for you?

**Comment by arvindr21** [comment]
Nope. The present url does not have the template parameters in it.

Hm, the link that's there should already work! Does it not work for you?

—
Reply to this email directly or view it on GitHub
<https://github.com/peers/peerjs-server/pull/66#issuecomment-75508749>.

**Comment by michelle** [comment]
Sure, but clicking it seems to fill in the right parameters, at least for
me. Oh well, better to be explicit. Thanks for the PR!

Michelle

On Mon, Feb 23, 2015 at 1:17 AM, Arvind Ravulavaru <notifications@github.com

**Comment by arvindr21** [comment]
Thanks!

**Pull request merged**
