### PR TITLE
Ignore heartbeat messages

### PR DESCRIPTION
**Pull request by dylannz**
Something like this would be great to avoid the "ERROR PeerServer:  Message unrecognized" messages when sending heartbeats as shown here: https://github.com/peers/peerjs/issues/227

### CODE REVIEW

**Comment by Masterxilo** [comment]
I totally agree

**Comment by maxpavlov** [comment]
@kidandcat, perhaps let's merge this PR?

**Comment by kidandcat** [comment]
Sure, sorry but I'm on Thailand right now, next weekend when I be back I'll
review everything and merge this PR.

**Comment by fresheneesz** [comment]
This is merged, but I still see the issue: "ERROR PeerServer:  Message unrecognized". What's going on? Has the version it was merged into been released?

**Comment by s-h-a-d-o-w** [comment]
@fresheneesz 
Seeing how this got merged about half a year before the actual heartbeat, maybe it was removed again within that time period, since it was thought that the heartbeat isn't going to happen anyway or something?

Personally, seeing how it seems like the library is currently undergoing either a complete rewrite or severe refactoring, I have simply created a patch in my project with `patch-package`, since this is the only issue that impacts me and it's just 3 lines.

**Pull request merged**
